// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: client.proto

#include "client.pb.h"
#include "client.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace window {

static const char* Window_method_names[] = {
  "/window.Window/MoveWindow",
};

std::unique_ptr< Window::Stub> Window::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Window::Stub> stub(new Window::Stub(channel));
  return stub;
}

Window::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_MoveWindow_(Window_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Window::Stub::MoveWindow(::grpc::ClientContext* context, const ::window::MoveMessage& request, ::window::ResponseMessage* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_MoveWindow_, context, request, response);
}

void Window::Stub::experimental_async::MoveWindow(::grpc::ClientContext* context, const ::window::MoveMessage* request, ::window::ResponseMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MoveWindow_, context, request, response, std::move(f));
}

void Window::Stub::experimental_async::MoveWindow(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::window::ResponseMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MoveWindow_, context, request, response, std::move(f));
}

void Window::Stub::experimental_async::MoveWindow(::grpc::ClientContext* context, const ::window::MoveMessage* request, ::window::ResponseMessage* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MoveWindow_, context, request, response, reactor);
}

void Window::Stub::experimental_async::MoveWindow(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::window::ResponseMessage* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_MoveWindow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::window::ResponseMessage>* Window::Stub::AsyncMoveWindowRaw(::grpc::ClientContext* context, const ::window::MoveMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::window::ResponseMessage>::Create(channel_.get(), cq, rpcmethod_MoveWindow_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::window::ResponseMessage>* Window::Stub::PrepareAsyncMoveWindowRaw(::grpc::ClientContext* context, const ::window::MoveMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::window::ResponseMessage>::Create(channel_.get(), cq, rpcmethod_MoveWindow_, context, request, false);
}

Window::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Window_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Window::Service, ::window::MoveMessage, ::window::ResponseMessage>(
          std::mem_fn(&Window::Service::MoveWindow), this)));
}

Window::Service::~Service() {
}

::grpc::Status Window::Service::MoveWindow(::grpc::ServerContext* context, const ::window::MoveMessage* request, ::window::ResponseMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace window

